import { Inter } from "next/font/google";
import "./globals.css";
// import { SnackbarProvider } from "notistack";
// import { Slide } from "@mui/material";
import Auth0ProviderWithHistory from "@/auth/auth0-provider-with-history";
import GlobalWrapper from "@/components/GlobalWrapper";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Gadgets for less",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <Script src="https://checkout.sandbox.dev.clover.com/sdk.js" async />
      </head>
      <Auth0ProviderWithHistory>
        <body className={inter.className}>
          <GlobalWrapper>{children}</GlobalWrapper>
        </body>
      </Auth0ProviderWithHistory>
    </html>
  );
}
